<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprogram" nsURI="https://no/tdt4250/2019/studyprogram" nsPrefix="no.tdt4250.2019.studyprogram">
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true" eOpposite="#//Course/department"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisaitions" upperBound="-1"
        eType="#//Specialisation" containment="true" eOpposite="#//Specialisation/programme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="years" lowerBound="2" upperBound="5"
        eType="#//Year"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Year">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SemesterType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true" eOpposite="#//Course/semester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" eType="#//Department"
        eOpposite="#//Department/courses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" eType="#//Semester"
        eOpposite="#//Semester/courses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programme" eType="#//Programme"
        eOpposite="#//Programme/specialisaitions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SemesterType">
    <eLiterals name="Fall" literal="Fall"/>
    <eLiterals name="Spring" value="1" literal="Spring"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseType">
    <eLiterals name="Obligatory" literal="Obligatory"/>
    <eLiterals name="Chosen" value="1" literal="Chosen"/>
  </eClassifiers>
</ecore:EPackage>
